---
title: "NEWS"
author: "R. Mark Sharp"
date: "03/28/2020"
output:
  github_document: default

---

  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# snprcspf 1.1.0 (20200328)
-   Have replaced dependence on Java for the Excel formatting. Using openxlsx
    package
-   Have cleaned up code for file name and file path management for the Excel
    input file names and paths

# snprcspf 1.0.9 (20200321)
-   Copied build instructions from nprcgenekeepr
-   Removed redundant copy of a function.

# snprcspf 1.0.8 (20200321)
-   Separated R code into seperate files for each function.
-   Created some data objects for testing and demonstration. This has
    created a dependency on R >= 3.5.0.

# snprcspf 1.0.7 (20190526)
-   Removed formating of Excel sheets to remove dependency on rJava used by
    XLConnect.
    As of 2019 May 26, Java 12 has a bug 
    \url{https://bugs.openjdk.java.net/browse/JDK-8221530} that prevents 
    the use of the XLConnect package. This version of snprcspf has removed 
    that dependency with the side effect of not providing formating within 
    the Excel workbook generated.

