library(snprcspf)
library(rmsutilityr)
context("Get antigen pairs from df$names")
antigens <- c("HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20",
              "HTLV-1/2", "SRV-2", "HVP-2", "SIV gp130", "SIV mac", "SRV gp-20"
)
test_that("Proper antigen pair list is created from antigens tested", {
  expect_identical(
    get_antigen_pairs(antigens), data.frame(agent = c("STLV", "SRV", "SIV", "BV"),
                                            a1 = c("HTLV-1/2", "SRV-2",
                                                   "SIV gp130", "BV glyco B"),
                                            a2 = c("STLV p21", "SRV gp-20",
                                                   "SIV mac", "HVP-2"),
                                            stringsAsFactors = FALSE))
})
